import { Category } from "@/types/category"
import { CurrencyPosition, DiscountType, ProductStatus } from "@/types/common"
import { Currency } from "@/types/currency"
import { ShopSettings } from "@/types/shopSettings"
import { Product } from "@/types/product"
import { Collection } from "@/types/collection"
import { ProductVariant } from "@/types/productVariant"
import { Coupon } from "@/types/coupon" 
// Currencies
export const mockCurrencies: Currency[] = [
  {
    id: "curr_1",
    code: "PEN",
    name: "Peruvian Sol",
    symbol: "S/",
    decimalPlaces: 2,
    symbolPosition: CurrencyPosition.BEFORE,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "curr_2",
    code: "USD",
    name: "US Dollar",
    symbol: "$",
    decimalPlaces: 2,
    symbolPosition: CurrencyPosition.BEFORE,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "curr_3",
    code: "EUR",
    name: "Euro",
    symbol: "€",
    decimalPlaces: 2,
    symbolPosition: CurrencyPosition.AFTER,
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

// Shop Settings
export const mockShopSettings: ShopSettings = {
  id: "shop_1",
  name: "Clefast",
  domain: "clefast.com",
  email: "info@clefast.com",
  shopOwner: "Juan Pérez",
  logo: "/logo.png",
  description: "Productos de limpieza industrial de alta calidad",
  address1: "Av. Industrial 123",
  address2: "Piso 2",
  city: "Lima",
  province: "Lima",
  provinceCode: "LIM",
  country: "Perú",
  countryCode: "PE",
  zip: "15001",
  phone: "+51 1 234 5678",
  defaultCurrency: mockCurrencies[0],
  defaultCurrencyId: mockCurrencies[0].id,
  acceptedCurrencies: mockCurrencies,
  multiCurrencyEnabled: true,
  taxesIncluded: true,
  taxValue: 18,
  maintenanceMode: false,
  multiLanguageEnabled: false,
  status: "active",
  liveChatEnabled: true,
  facebookUrl: "https://facebook.com/clefast",
  instagramUrl: "https://instagram.com/clefast",
  twitterUrl: "https://twitter.com/clefast",
  youtubeUrl: "https://youtube.com/clefast",
  createdAt: new Date(),
  updatedAt: new Date(),
}

// Helper function to get a product image
function getProductImage(index: number): string {
  return `/product${(index % 10) + 1}.png`
}

// Categories
export const mockCategories: Category[] = [
  {
    id: "cat_1",
    name: "Detergentes",
    slug: "detergentes",
    description: "Productos de limpieza industrial",
    imageUrl: "/categories/detergentes.jpg",
    children: [
      {
        id: "cat_1_1",
        name: "Detergentes Líquidos",
        slug: "detergentes-liquidos",
        description: "Detergentes líquidos para uso industrial",
        imageUrl: "/categories/detergentes-liquidos.jpg",
        children: [],
        products: [],
        metaTitle: "Detergentes Líquidos Industriales | Clefast",
        metaDescription: "Descubre nuestra línea de detergentes líquidos industriales de alta calidad.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "cat_1_2",
        name: "Detergentes en Polvo",
        slug: "detergentes-polvo",
        description: "Detergentes en polvo para uso industrial",
        imageUrl: "/categories/detergentes-polvo.jpg",
        children: [],
        products: [],
        metaTitle: "Detergentes en Polvo Industriales | Clefast",
        metaDescription: "Explora nuestra gama de detergentes en polvo para uso industrial.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    products: [],
    metaTitle: "Detergentes Industriales | Clefast",
    metaDescription: "Descubre nuestra línea completa de detergentes industriales de alta calidad.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "cat_2",
    name: "Desinfectantes",
    slug: "desinfectantes",
    description: "Productos para desinfección industrial",
    imageUrl: "/categories/desinfectantes.jpg",
    children: [
      {
        id: "cat_2_1",
        name: "Desinfectantes de Superficies",
        slug: "desinfectantes-superficies",
        description: "Desinfectantes para todo tipo de superficies",
        imageUrl: "/categories/desinfectantes-superficies.jpg",
        children: [],
        products: [],
        metaTitle: "Desinfectantes de Superficies | Clefast",
        metaDescription: "Desinfectantes potentes para todo tipo de superficies industriales.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "cat_2_2",
        name: "Desinfectantes Especializados",
        slug: "desinfectantes-especializados",
        description: "Desinfectantes para usos específicos",
        imageUrl: "/categories/desinfectantes-especializados.jpg",
        children: [],
        products: [],
        metaTitle: "Desinfectantes Especializados | Clefast",
        metaDescription: "Desinfectantes especializados para necesidades industriales específicas.",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    products: [],
    metaTitle: "Desinfectantes Industriales | Clefast",
    metaDescription: "Explora nuestra gama completa de desinfectantes industriales potentes y efectivos.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "cat_3",
    name: "Limpiadores Especializados",
    slug: "limpiadores-especializados",
    description: "Productos para limpieza de superficies específicas",
    imageUrl: "/categories/limpiadores-especializados.jpg",
    children: [],
    products: [],
    metaTitle: "Limpiadores Especializados | Clefast",
    metaDescription: "Soluciones de limpieza especializadas para todo tipo de superficies industriales.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "cat_4",
    name: "Equipos de Limpieza",
    slug: "equipos-limpieza",
    description: "Maquinaria y equipos para limpieza industrial",
    imageUrl: "/categories/equipos-limpieza.jpg",
    children: [],
    products: [],
    metaTitle: "Equipos de Limpieza Industrial | Clefast",
    metaDescription: "Descubre nuestra selección de equipos y maquinaria para limpieza industrial.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "cat_5",
    name: "Productos Ecológicos",
    slug: "productos-ecologicos",
    description: "Productos de limpieza amigables con el medio ambiente",
    imageUrl: "/categories/productos-ecologicos.jpg",
    children: [],
    products: [],
    metaTitle: "Productos de Limpieza Ecológicos | Clefast",
    metaDescription: "Explora nuestra línea de productos de limpieza industrial ecológicos y sostenibles.",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

// Collections
export const mockCollections: Collection[] = [
  {
    id: "col_1",
    title: "Productos Destacados",
    slug: "destacados",
    description: "Nuestros productos más populares",
    imageUrl: "/collections/destacados.jpg",
    isFeatured: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "col_2",
    title: "Nuevos Lanzamientos",
    slug: "nuevos-lanzamientos",
    description: "Los últimos productos añadidos a nuestro catálogo",
    imageUrl: "/collections/nuevos-lanzamientos.jpg",
    isFeatured: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

// Products
export const mockProducts: Product[] = [
  {
    id: "prod_1",
    title: "Detergente Industrial Premium",
    description: "Detergente líquido concentrado de alta eficiencia para lavandería industrial.",
    slug: "detergente-industrial-premium",
    vendor: "Clefast",
    fbt: {},
    allowBackorder: false,
    releaseDate: new Date("2023-01-01"),
    status: ProductStatus.ACTIVE,
    categories: [mockCategories[0], mockCategories[0].children[0]],
    variants: [
      {
        id: "var_1",
        productId: "prod_1",
        title: "Bidón 20L",
        sku: "DET-IND-20L",
        attributes: {
          size: "20L",
          concentration: "Alta",
        },
        isActive: true,
        imageUrl: getProductImage(0),
        prices: [
          {
            id: "price_1",
            variantId: "var_1",
            currencyId: mockCurrencies[0].id,
            currency: mockCurrencies[0],
            price: 199.9,
            originalPrice: 249.9,
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
        inventoryQuantity: 100,
        weightValue: 20,
        position: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    imageUrls: [getProductImage(0)],
    collections: [mockCollections[0]],
    createdAt: new Date(),
    updatedAt: new Date(),
    metaTitle: "Detergente Industrial Premium | Clefast",
    metaDescription: "Detergente líquido concentrado de alta eficiencia para lavandería industrial. Máximo poder limpiador.",
    coupons: []
  },
  {
    id: "prod_2",
    title: "Desinfectante Multiusos",
    description: "Desinfectante de amplio espectro para todo tipo de superficies.",
    slug: "desinfectante-multiusos",
    vendor: "Clefast",
    fbt: {},
    allowBackorder: false,
    releaseDate: new Date("2023-01-01"),
    status: ProductStatus.ACTIVE,
    categories: [mockCategories[1], mockCategories[1].children[0]],
    variants: [
      {
        id: "var_2",
        productId: "prod_2",
        title: "Botella 1L",
        sku: "DES-MUL-1L",
        attributes: {
          size: "1L",
          concentration: "Alta",
        },
        isActive: true,
        imageUrl: getProductImage(1),
        prices: [
          {
            id: "price_2",
            variantId: "var_2",
            currencyId: mockCurrencies[0].id,
            currency: mockCurrencies[0],
            price: 24.9,
            originalPrice: 29.88,
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
        inventoryQuantity: 200,
        weightValue: 1,
        position: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    imageUrls: [getProductImage(1)],
    collections: [mockCollections[0], mockCollections[1]],
    createdAt: new Date(),
    updatedAt: new Date(),
    metaTitle: "Desinfectante Multiusos | Clefast",
    metaDescription: "Desinfectante de amplio espectro para todo tipo de superficies. Descubre la calidad de Clefast en limpieza industrial.",
    coupons: []
  },
  {
    id: "prod_3",
    title: "Limpiador de Vidrios Industrial",
    description: "Limpiador especializado para vidrios y superficies brillantes en entornos industriales.",
    slug: "limpiador-vidrios-industrial",
    vendor: "Clefast",
    fbt: {},
    allowBackorder: false,
    releaseDate: new Date("2023-01-01"),
    status: ProductStatus.ACTIVE,
    categories: [mockCategories[2]],
    variants: [
      {
        id: "var_3",
        productId: "prod_3",
        title: "Botella 2L con Pulverizador",
        sku: "LIM-VID-2L",
        attributes: {
          size: "2L",
          concentration: "Alta",
        },
        isActive: true,
        imageUrl: getProductImage(2),
        prices: [
          {
            id: "price_3",
            variantId: "var_3",
            currencyId: mockCurrencies[0].id,
            currency: mockCurrencies[0],
            price: 34.9,
            originalPrice: 41.88,
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
        inventoryQuantity: 120,
        weightValue: 2,
        position: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    imageUrls: [getProductImage(2)],
    collections: [mockCollections[0]],
    createdAt: new Date(),
    updatedAt: new Date(),
    metaTitle: "Limpiador de Vidrios Industrial | Clefast",
    metaDescription: "Limpiador especializado para vidrios y superficies brillantes en entornos industriales. Descubre la calidad de Clefast en limpieza industrial.",
    coupons: []
  },
  {
    id: "prod_4",
    title: "Aspiradora Industrial",
    description: "Aspiradora potente para uso industrial y comercial.",
    slug: "aspiradora-industrial",
    vendor: "Clefast",
    fbt: {},
    allowBackorder: false,
    releaseDate: new Date("2023-01-01"),
    status: ProductStatus.ACTIVE,
    categories: [mockCategories[3]],
    variants: [
      {
        id: "var_4",
        productId: "prod_4",
        title: "Modelo Estándar",
        sku: "ASP-IND-STD",
        attributes: {
          size: "Estándar",
          concentration: "Alta",
        },
        isActive: true,
        imageUrl: getProductImage(3),
        prices: [
          {
            id: "price_4",
            variantId: "var_4",
            currencyId: mockCurrencies[0].id,
            currency: mockCurrencies[0],
            price: 599.9,
            originalPrice: 719.88,
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
        inventoryQuantity: 50,
        weightValue: 1,
        position: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    imageUrls: [getProductImage(3)],
    collections: [mockCollections[1]],
    createdAt: new Date(),
    updatedAt: new Date(),
    metaTitle: "Aspiradora Industrial | Clefast",
    metaDescription: "Aspiradora potente para uso industrial y comercial. Descubre la calidad de Clefast en limpieza industrial.",
    coupons: []
  },
  {
    id: "prod_5",
    title: "Limpiador Ecológico Multiusos",
    description: "Limpiador biodegradable para múltiples superficies.",
    slug: "limpiador-ecologico-multiusos",
    vendor: "Clefast",
    fbt: {},
    allowBackorder: false,
    releaseDate: new Date("2023-01-01"),
    status: ProductStatus.ACTIVE,
    categories: [mockCategories[4]],
    variants: [
      {
        id: "var_5",
        productId: "prod_5",
        title: "Botella 1L",
        sku: "ECO-MUL-1L",
        attributes: {
          size: "1L",
          concentration: "Alta",
        },
        isActive: true,
        imageUrl: getProductImage(4),
        prices: [
          {
            id: "price_5",
            variantId: "var_5",
            currencyId: mockCurrencies[0].id,
            currency: mockCurrencies[0],
            price: 29.9,
            originalPrice: 35.88,
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
        inventoryQuantity: 150,
        weightValue: 1,
        position: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    imageUrls: [getProductImage(4)],
    collections: [mockCollections[0], mockCollections[1]],
    createdAt: new Date(),
    updatedAt: new Date(),
    metaTitle: "Limpiador Ecológico Multiusos | Clefast",
    metaDescription: "Limpiador biodegradable para múltiples superficies. Descubre la calidad de Clefast en limpieza industrial.",
    coupons: []
  },
  {
    id: "prod_6",
    title: "Detergente en Polvo Industrial",
    description: "Detergente en polvo de alta eficiencia para lavandería industrial.",
    slug: "detergente-polvo-industrial",
    vendor: "Clefast",
    fbt: {},
    allowBackorder: false,
    releaseDate: new Date("2023-01-01"),
    status: ProductStatus.ACTIVE,
    categories: [mockCategories[0], mockCategories[0].children[1]],
    variants: [
      {
        id: "var_6",
        productId: "prod_6",
        title: "Saco 25kg",
        sku: "DET-POL-25KG",
        attributes: {
          size: "25kg",
          concentration: "Alta",
        },
        isActive: true,
        imageUrl: getProductImage(5),
        prices: [
          {
            id: "price_6",
            variantId: "var_6",
            currencyId: mockCurrencies[0].id,
            currency: mockCurrencies[0],
            price: 179.9,
            originalPrice: 215.88,
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
        inventoryQuantity: 80,
        weightValue: 25,
        position: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    imageUrls: [getProductImage(5)],
    collections: [mockCollections[0]],
    createdAt: new Date(),
    updatedAt: new Date(),
    metaTitle: "Detergente en Polvo Industrial | Clefast",
    metaDescription: "Detergente en polvo de alta eficiencia para lavandería industrial. Descubre la calidad de Clefast en limpieza industrial.",
    coupons: []
  },
  {
    id: "prod_7",
    title: "Desinfectante para Alimentos",
    description: "Desinfectante especializado para áreas de preparación de alimentos.",
    slug: "desinfectante-alimentos",
    vendor: "Clefast",
    fbt: {},
    allowBackorder: false,
    releaseDate: new Date("2023-01-01"),
    status: ProductStatus.ACTIVE,
    categories: [mockCategories[1], mockCategories[1].children[1]],
    variants: [
      {
        id: "var_7",
        productId: "prod_7",
        title: "Botella 5L",
        sku: "DES-ALI-5L",
        attributes: {
          size: "5L",
          concentration: "Alta",
        },
        isActive: true,
        imageUrl: getProductImage(6),
        prices: [
          {
            id: "price_7",
            variantId: "var_7",
            currencyId: mockCurrencies[0].id,
            currency: mockCurrencies[0],
            price: 89.9,
            originalPrice: 107.88,
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
        inventoryQuantity: 100,
        weightValue: 5,
        position: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    imageUrls: [getProductImage(6)],
    collections: [mockCollections[1]],
    createdAt: new Date(),
    updatedAt: new Date(),
    metaTitle: "Desinfectante para Alimentos | Clefast",
    metaDescription: "Desinfectante especializado para áreas de preparación de alimentos. Descubre la calidad de Clefast en limpieza industrial.",
    coupons: []
  },
  {
    id: "prod_8",
    title: "Limpiador de Grasa Industrial",
    description: "Potente desengrasante para uso en cocinas industriales y talleres.",
    slug: "limpiador-grasa-industrial",
    vendor: "Clefast",
    fbt: {},
    allowBackorder: false,
    releaseDate: new Date("2023-01-01"),
    status: ProductStatus.ACTIVE,
    categories: [mockCategories[2]],
    variants: [
      {
        id: "var_8",
        productId: "prod_8",
        title: "Bidón 10L",
        sku: "LIM-GRA-10L",
        attributes: {
          size: "10L",
          concentration: "Alta",
        },
        isActive: true,
        imageUrl: getProductImage(7),
        prices: [
          {
            id: "price_8",
            variantId: "var_8",
            currencyId: mockCurrencies[0].id,
            currency: mockCurrencies[0],
            price: 129.9,
            originalPrice: 155.88,
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
        inventoryQuantity: 70,
        weightValue: 10,
        position: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    imageUrls: [getProductImage(7)],
    collections: [mockCollections[0]],
    createdAt: new Date(),
    updatedAt: new Date(),
    metaTitle: "Limpiador de Grasa Industrial | Clefast",
    metaDescription: "Potente desengrasante para uso en cocinas industriales y talleres. Descubre la calidad de Clefast en limpieza industrial.",
    coupons: []
  },
  {
    id: "prod_9",
    title: "Máquina Fregadora Industrial",
    description: "Fregadora automática para grandes superficies industriales.",
    slug: "maquina-fregadora-industrial",
    vendor: "Clefast",
    fbt: {},
    allowBackorder: false,
    releaseDate: new Date("2023-01-01"),
    status: ProductStatus.ACTIVE,
    categories: [mockCategories[3]],
    variants: [
      {
        id: "var_9",
        productId: "prod_9",
        title: "Modelo Grande",
        sku: "FRE-IND-GDE",
        attributes: {
          size: "Grande",
          concentration: "Alta",
        },
        isActive: true,
        imageUrl: getProductImage(8),
        prices: [
          {
            id: "price_9",
            variantId: "var_9",
            currencyId: mockCurrencies[0].id,
            currency: mockCurrencies[0],
            price: 2999.9,
            originalPrice: 3599.88,
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
        inventoryQuantity: 20,
        weightValue: 1,
        position: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    imageUrls: [getProductImage(8)],
    collections: [mockCollections[1]],
    createdAt: new Date(),
    updatedAt: new Date(),
    metaTitle: "Máquina Fregadora Industrial | Clefast",
    metaDescription: "Fregadora automática para grandes superficies industriales. Descubre la calidad de Clefast en limpieza industrial.",
    coupons: []
  },
  {
    id: "prod_10",
    title: "Jabón de Manos Ecológico",
    description: "Jabón de manos biodegradable y suave con la piel.",
    slug: "jabon-manos-ecologico",
    vendor: "Clefast",
    fbt: {},
    allowBackorder: false,
    releaseDate: new Date("2023-01-01"),
    status: ProductStatus.ACTIVE,
    categories: [mockCategories[4]],
    variants: [
      {
        id: "var_10",
        productId: "prod_10",
        title: "Botella 500ml",
        sku: "ECO-JAB-500ML",
        attributes: {
          size: "500ml",
          concentration: "Alta",
        },
        isActive: true,
        imageUrl: getProductImage(9),
        prices: [
          {
            id: "price_10",
            variantId: "var_10",
            currencyId: mockCurrencies[0].id,
            currency: mockCurrencies[0],
            price: 19.9,
            originalPrice: 23.88,
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
        inventoryQuantity: 200,
        weightValue: 500,
        position: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    imageUrls: [getProductImage(9)],
    collections: [mockCollections[0], mockCollections[1]],
    createdAt: new Date(),
    updatedAt: new Date(),
    metaTitle: "Jabón de Manos Ecológico | Clefast",
    metaDescription: "Jabón de manos biodegradable y suave con la piel. Descubre la calidad de Clefast en limpieza industrial.",
    coupons: []
  },
  {
    id: "prod_11",
    title: "Detergente Líquido Concentrado",
    description: "Detergente líquido altamente concentrado para uso industrial.",
    slug: "detergente-liquido-concentrado",
    vendor: "Clefast",
    fbt: {},
    allowBackorder: false,
    releaseDate: new Date("2023-01-01"),
    status: ProductStatus.ACTIVE,
    categories: [mockCategories[0], mockCategories[0].children[0]],
    variants: [
      {
        id: "var_11",
        productId: "prod_11",
        title: "Bidón 10L",
        sku: "DET-LIQ-10L",
        attributes: {
          size: "10L",
          concentration: "Alta",
        },
        isActive: true,
        imageUrl: getProductImage(10),
        prices: [
          {
            id: "price_11",
            variantId: "var_11",
            currencyId: mockCurrencies[0].id,
            currency: mockCurrencies[0],
            price: 149.9,
            originalPrice: 179.88,
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
        inventoryQuantity: 90,
        weightValue: 10,
        position: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    imageUrls: [getProductImage(10)],
    collections: [mockCollections[0]],
    createdAt: new Date(),
    updatedAt: new Date(),
    metaTitle: "Detergente Líquido Concentrado | Clefast",
    metaDescription: "Detergente líquido altamente concentrado para uso industrial. Descubre la calidad de Clefast en limpieza industrial.",
    coupons: []
  },
  {
    id: "prod_12",
    title: "Desinfectante para Hospitales",
    description: "Desinfectante de grado hospitalario para áreas críticas.",
    slug: "desinfectante-hospitales",
    vendor: "Clefast",
    fbt: {},
    allowBackorder: false,
    releaseDate: new Date("2023-01-01"),
    status: ProductStatus.ACTIVE,
    categories: [mockCategories[1], mockCategories[1].children[1]],
    variants: [
      {
        id: "var_12",
        productId: "prod_12",
        title: "Botella 2L",
        sku: "DES-HOS-2L",
        attributes: {
          size: "2L",
          concentration: "Alta",
        },
        isActive: true,
        imageUrl: getProductImage(11),
        prices: [
          {
            id: "price_12",
            variantId: "var_12",
            currencyId: mockCurrencies[0].id,
            currency: mockCurrencies[0],
            price: 59.9,
            originalPrice: 71.88,
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
        inventoryQuantity: 120,
        weightValue: 2,
        position: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    imageUrls: [getProductImage(11)],
    collections: [mockCollections[1]],
    createdAt: new Date(),
    updatedAt: new Date(),
    metaTitle: "Desinfectante para Hospitales | Clefast",
    metaDescription: "Desinfectante de grado hospitalario para áreas críticas. Descubre la calidad de Clefast en limpieza industrial.",
    coupons: []
  },
  {
    id: "prod_13",
    title: "Limpiador de Alfombras",
    description: "Limpiador especializado para alfombras y tapicerías.",
    slug: "limpiador-alfombras",
    vendor: "Clefast",
    fbt: {},
    allowBackorder: false,
    releaseDate: new Date("2023-01-01"),
    status: ProductStatus.ACTIVE,
    categories: [mockCategories[2]],
    variants: [
      {
        id: "var_13",
        productId: "prod_13",
        title: "Botella 1L",
        sku: "LIM-ALF-1L",
        attributes: {
          size: "1L",
          concentration: "Alta",
        },
        isActive: true,
        imageUrl: getProductImage(12),
        prices: [
          {
            id: "price_13",
            variantId: "var_13",
            currencyId: mockCurrencies[0].id,
            currency: mockCurrencies[0],
            price: 39.9,
            originalPrice: 47.88,
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
        inventoryQuantity: 150,
        weightValue: 1,
        position: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    imageUrls: [getProductImage(12)],
    collections: [mockCollections[0]],
    createdAt: new Date(),
    updatedAt: new Date(),
    metaTitle: "Limpiador de Alfombras | Clefast",
    metaDescription: "Limpiador especializado para alfombras y tapicerías. Descubre la calidad de Clefast en limpieza industrial.",
    coupons: []
  },
  {
    id: "prod_14",
    title: "Carrito de Limpieza Multiusos",
    description: "Carrito de limpieza versátil para uso en hoteles y oficinas.",
    slug: "carrito-limpieza-multiusos",
    vendor: "Clefast",
    fbt: {},
    allowBackorder: false,
    releaseDate: new Date("2023-01-01"),
    status: ProductStatus.ACTIVE,
    categories: [mockCategories[3]],
    variants: [
      {
        id: "var_14",
        productId: "prod_14",
        title: "Modelo Estándar",
        sku: "CAR-LIM-STD",
        attributes: {
          size: "Estándar",
          concentration: "Alta",
        },
        isActive: true,
        imageUrl: getProductImage(13),
        prices: [
          {
            id: "price_14",
            variantId: "var_14",
            currencyId: mockCurrencies[0].id,
            currency: mockCurrencies[0],
            price: 299.9,
            originalPrice: 359.88,
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
        inventoryQuantity: 40,
        weightValue: 1,
        position: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    imageUrls: [getProductImage(13)],
    collections: [mockCollections[1]],
    createdAt: new Date(),
    updatedAt: new Date(),
    metaTitle: "Carrito de Limpieza Multiusos | Clefast",
    metaDescription: "Carrito de limpieza versátil para uso en hoteles y oficinas. Descubre la calidad de Clefast en limpieza industrial.",
    coupons: []
  },
  {
    id: "prod_15",
    title: "Desengrasante Ecológico",
    description: "Desengrasante biodegradable para cocinas y áreas de procesamiento de alimentos.",
    slug: "desengrasante-ecologico",
    vendor: "Clefast",
    fbt: {},
    allowBackorder: false,
    releaseDate: new Date("2023-01-01"),
    status: ProductStatus.ACTIVE,
    categories: [mockCategories[4]],
    variants: [
      {
        id: "var_15",
        productId: "prod_15",
        title: "Botella 750ml",
        sku: "ECO-DES-750ML",
        attributes: {
          size: "750ml",
          concentration: "Alta",
        },
        isActive: true,
        imageUrl: getProductImage(14),
        prices: [
          {
            id: "price_15",
            variantId: "var_15",
            currencyId: mockCurrencies[0].id,
            currency: mockCurrencies[0],
            price: 24.9,
            originalPrice: 29.88,
            createdAt: new Date(),
            updatedAt: new Date(),
          },
        ],
        inventoryQuantity: 180,
        weightValue: 750,
        position: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    imageUrls: [getProductImage(14)],
    collections: [mockCollections[0], mockCollections[1]],
    createdAt: new Date(),
    updatedAt: new Date(),
    metaTitle: "Desengrasante Ecológico | Clefast",
    metaDescription: "Desengrasante biodegradable para cocinas y áreas de procesamiento de alimentos. Descubre la calidad de Clefast en limpieza industrial.",
    coupons: []
  },
]

// Update the rest of the products
mockProducts.forEach((product, index) => {
  product.fbt = {}
  product.allowBackorder = false
  product.releaseDate = new Date(new Date().setMonth(new Date().getMonth() - Math.floor(Math.random() * 12)))
  product.metaTitle = `${product.title} | Clefast`
  product.metaDescription = `${product.description} Descubre la calidad de Clefast en limpieza industrial.`
  product.imageUrls = [getProductImage(index)]
  product.variants = product.variants.map((variant) => ({
    ...variant,
    imageUrl: getProductImage(index),
    prices: variant.prices.map((price) => ({
      ...price,
      originalPrice: price.originalPrice || price.price * 1.2, // If no original price, set it 20% higher
    })),
  }))
})

// Update category products
mockCategories.forEach((category) => {
  category.products = mockProducts.filter((product) => product.categories.some((cat) => cat.id === category.id))

  if (category.children) {
    category.children.forEach((subCategory) => {
      subCategory.products = mockProducts.filter((product) =>
        product.categories.some((cat) => cat.id === subCategory.id),
      )
    })
  }
})

// Ensure parent categories include products from their subcategories
mockCategories.forEach((category) => {
  if (category.children) {
    const subCategoryProducts = category.children.flatMap((subCat) => subCat.products)
    category.products = [...new Set([...category.products, ...subCategoryProducts])]
  }
})

// Log the number of products in each category for verification
console.log("Products per category:")
mockCategories.forEach((category) => {
  console.log(`${category.name}: ${category.products.length} products`)
  if (category.children) {
    category.children.forEach((subCategory) => {
      console.log(`  ${subCategory.name}: ${subCategory.products.length} products`)
    })
  }
})

// Shipping Methods
export const mockShippingMethods = [
  {
    id: "sm_1",
    name: "Envío Estándar",
    description: "Entrega en 3-5 días hábiles",
    prices: [
      {
        id: "smp_1",
        shippingMethodId: "sm_1",
        currencyId: mockCurrencies[0].id,
        price: 15,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    estimatedDeliveryTime: "3-5 días hábiles",
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "sm_2",
    name: "Envío Express",
    description: "Entrega en 1-2 días hábiles",
    prices: [
      {
        id: "smp_2",
        shippingMethodId: "sm_2",
        currencyId: mockCurrencies[0].id,
        price: 25,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    estimatedDeliveryTime: "1-2 días hábiles",
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

// Coupons
export const mockCoupons: Coupon[] = [
  {
    id: "coup_1",
    code: "BIENVENIDO10",
    description: "10% de descuento en tu primera compra",
    type: DiscountType.PERCENTAGE,
    value: 10,
    minPurchase: 100,
    maxUses: 1,
    usedCount: 0,
    startDate: new Date(),
    endDate: new Date(new Date().setMonth(new Date().getMonth() + 1)),
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "coup_2",
    code: "ENVIOGRATIS",
    description: "Envío gratis en compras superiores a S/ 300",
    type: DiscountType.FREE_SHIPPING,
    value: 0,
    minPurchase: 300,
    maxUses: 3,
    usedCount: 0,
    startDate: new Date(),
    endDate: new Date(new Date().setFullYear(new Date().getFullYear() + 1)),
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

